<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DeviceIdentifierLibrary">
      <HintPath>..\DeviceIdentifierLibrary\bin\Debug\net10.0\DeviceIdentifierLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
